#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

HOOK_FILE=$1
COMMIT_MSG=`head -n1 $HOOK_FILE`
PATTERN="^[A-Z][A-Z0-9]+-[0-9]+"
if [[ ! ${COMMIT_MSG} =~ $PATTERN ]]; then
  echo ""
  echo "    ERROR! Bad commit message. "
  echo "    '$COMMIT_MSG' is missing JIRA Ticket Number."
  echo "    example: 'AP-12: Please write correct ticket number'"
  echo ""
  exit 1
fi

if [ ${#COMMIT_MSG} -gt 80 ] || [ ${#COMMIT_MSG} -lt 10 ] ; then
    echo ""
    echo "    ERROR! commit message length is invalid. "
    echo ""
    exit 1
fi

